services:
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports:
      - "8000:8000"

  dynamodb_init:
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: DummyKeyId
      AWS_SECRET_ACCESS_KEY: DummyKey
    command: >-
      dynamodb create-table 
          --table-name Books 
          --attribute-definitions AttributeName=id,AttributeType=S 
          --key-schema AttributeName=id,KeyType=HASH 
          --billing-mode PAY_PER_REQUEST 
          --endpoint-url http://dynamodb:8000 
          --region dummy-region

  dynamodb_populate:
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: DummyKeyId
      AWS_SECRET_ACCESS_KEY: DummyKey
    command: >-
      dynamodb batch-write-item
          --request-items '{
              "Books": [
                {
                  "PutRequest": {
                    "Item": {
                      "id": {"S": "9781234567890"},
                      "title": {"S": "No One You Know"},
                      "pages": {"N": "389"},
                      "pages_done": {"N": "0"}
                    }
                  }
                },
                {
                  "PutRequest": {
                    "Item": {
                      "id": {"S": "9780987654321"},
                      "title": {"S": "Anatomy"},
                      "pages": {"N": "560"},
                      "pages_done": {"N": "560"}
                    }
                  }
                },
                {
                  "PutRequest": {
                    "Item": {
                      "id": {"S": "9781122334455"},
                      "title": {"S": "Sapiens"},
                      "pages": {"N": "56"},
                      "pages_done": {"N": "34"}
                    }
                  }
                }
              ]
            }'
          --endpoint-url http://dynamodb:8000
          --region dummy-region
    depends_on:
      - dynamodb_init