version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "aws-serverless-sample"

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "aws-serverless-sample"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.local_start_api.parameters]
warm_containers = "EAGER"
