AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  AWSEndpointURL:
    Type: String
    Default: ""

Globals:
  Function:
    MemorySize: 128
    Architectures: [ "arm64" ]
    Handler: bootstrap
    Runtime: provided.al2023
    Timeout: 5
    Tracing: Active
    Environment:
      Variables:
        TABLE: !Ref Table
        AWS_ENDPOINT_URL: !Ref AWSEndpointURL

Resources:
  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/cmd/lambda/get
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: !GetAtt Table.Arn
    Metadata:
      BuildMethod: makefile

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"